version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: giphy-app:latest
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        networks:
            - giphy-network
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - giphy-network
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: giphydb
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: giphyuser
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - giphy-network

networks:
    giphy-network:

volumes:
    dbdata:
    src:

