version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: giphy-app:latest
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
            - /var/www/vendor/
            - /var/www/node_modules
        depends_on:
            - mysql
        networks:
            - giphy-network
    nginx:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        depends_on:
            - php
            - mysql
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - /var/www/vendor
            - /var/www/node_modules
        networks:
            - giphy-network
    mysql:
        build:
            context: docker/mysql
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - giphy-network

networks:
    giphy-network:

volumes:
    src:

